logging:
  level: INFO
  loggers:
    com.company: DEBUG

database:

  driverClass: com.mysql.cj.jdbc.Driver
  # the username
  user: root
  # the password
  password: qazse@ZSEDC@1
  # the JDBC URL; the database is called geolocation
  url: jdbc:mysql://localhost:3306/geolocation


#  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.MySQLDialect
    console.enabled: true

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyApplication Health Check */ SELECT 1"

  # the minimum number of connections to keep open
  minSize: 8

  # the maximum number of connections to keep open
  maxSize: 32
#
#  # whether idle connections should be validated
#  checkConnectionWhileIdle: false